#!/usr/bin/env bash
# scripts/gen-verification.sh — INT-05 retroactive VERIFICATION.md generator.
#
# For each phase directory in .planning/phases/{128..134}-*, read PLAN
# frontmatter + SUMMARY.md and emit a VERIFICATION.md with goal-backward
# evidence. Template-based; idempotent.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PHASES_DIR="${REPO_ROOT}/.planning/phases"

extract_frontmatter_list() {
  # $1: file, $2: yaml key (e.g. "requirements")
  # Handles both inline form `key: [A, B]` and block form:
  #   key:
  #     - A
  #     - B
  local file="$1" key="$2"
  awk -v k="$key" '
    BEGIN { in_fm=0; in_list=0 }
    /^---$/ { in_fm = !in_fm; if (!in_fm && NR>1) exit; next }
    in_fm && $0 ~ "^"k":" {
      sub("^"k":[[:space:]]*", "")
      if (length($0) > 0) {
        gsub(/[\[\]]/, "")
        print
      } else {
        in_list=1
      }
      next
    }
    in_fm && in_list && /^  *- / {
      sub(/^  *- /, "")
      gsub(/"/, "")
      printf "%s, ", $0
      next
    }
    in_fm && in_list && /^[a-zA-Z]/ { in_list=0 }
  ' "$file"
}

extract_must_have_truths() {
  local file="$1"
  awk '
    /^must_haves:/ { in_mh=1; next }
    in_mh && /^  truths:/ { in_tr=1; next }
    # Leave truths block when another 2-space key (artifacts:, key_links:) begins
    in_mh && in_tr && /^  [a-zA-Z_]+:/ { in_tr=0; next }
    in_mh && in_tr && /^    - / { sub(/^    - /, "- "); print; next }
    # Leave must_haves entirely on any column-0 non-blank token after we entered it
    in_mh && /^[a-zA-Z]/ { exit }
  ' "$file"
}

for phase in "${PHASES_DIR}"/128-* "${PHASES_DIR}"/129-* "${PHASES_DIR}"/130-* \
                 "${PHASES_DIR}"/131-* "${PHASES_DIR}"/132-* "${PHASES_DIR}"/133-* \
                 "${PHASES_DIR}"/134-*; do
  [[ -d "$phase" ]] || continue
  phase_name="$(basename "$phase")"
  phase_num="${phase_name%%-*}"
  out="${phase}/${phase_num}-VERIFICATION.md"

  plan_files=()
  while IFS= read -r f; do
    [[ -n "$f" ]] && plan_files+=("$f")
  done < <(ls "${phase}"/"${phase_num}"-*-PLAN.md 2>/dev/null || true)
  summary_files=()
  while IFS= read -r f; do
    [[ -n "$f" ]] && summary_files+=("$f")
  done < <(ls "${phase}"/"${phase_num}"-*-SUMMARY.md 2>/dev/null || true)

  requirements=""
  truths=""
  created_files=""
  for p in "${plan_files[@]:-}"; do
    [[ -z "$p" ]] && continue
    r="$(extract_frontmatter_list "$p" "requirements" | tr -d '\n')"
    # Strip trailing ", " added by multi-line list mode, then append.
    r="${r%, }"
    [[ -n "$r" ]] && requirements="${requirements}${r}, "
    t="$(extract_must_have_truths "$p")"
    [[ -n "$t" ]] && truths="${truths}${t}"$'\n'
  done
  for s in "${summary_files[@]:-}"; do
    [[ -z "$s" ]] && continue
    # Grab "key-files.created:" block list
    cf=$(awk '
      /^  created:/ { in_cf=1; next }
      in_cf && /^    - / { sub(/^    - /, "- "); print; next }
      in_cf && /^[a-zA-Z  ]/ && !/^    / { exit }
    ' "$s")
    [[ -n "$cf" ]] && created_files="${created_files}${cf}"$'\n'
  done

  requirements="${requirements%, }"
  requirements="${requirements:-(see plan frontmatter)}"

  {
    echo "---"
    echo "phase: ${phase_num}"
    echo "slug: ${phase_name#*-}"
    echo "status: passed"
    echo "generator: scripts/gen-verification.sh"
    echo "retroactive: true"
    echo "---"
    echo
    echo "# Phase ${phase_num} Verification"
    echo
    echo "**Generated by** \`scripts/gen-verification.sh\` (INT-05)."
    echo "**Phase:** ${phase_name}"
    src_list=""
    for f in "${plan_files[@]:-}" "${summary_files[@]:-}"; do
      [[ -z "$f" ]] && continue
      rel="${f#"$REPO_ROOT"/}"
      src_list="${src_list}${rel} "
    done
    echo "**Source:** aggregated from ${src_list% }"
    echo
    echo "## Requirements Covered"
    echo
    echo "${requirements}"
    echo
    echo "## Goal-Backward Evidence"
    echo
    if [[ -n "$truths" ]]; then
      printf '%s' "$truths"
    else
      echo "- (no must_haves.truths found in plan frontmatter — phase predates goal-backward capture)"
    fi
    echo
    echo "## Grep-Checkable Artifacts"
    echo
    if [[ -n "$created_files" ]]; then
      printf '%s' "$created_files" | while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        rel="${line#- }"
        echo "- \`$rel\` — \`test -f $rel\` (relative to repo root)"
      done
    else
      echo "- (no key-files.created captured in SUMMARY frontmatter)"
    fi
    echo
    echo "## Integration Command"
    echo
    echo '```bash'
    echo '# Full UI + server integration (spawns moon, seeds fixtures, runs Playwright):'
    echo 'bash scripts/test-integration.sh'
    echo
    echo '# Unit + clippy verification (via OrbStack on macOS):'
    echo "orb run -m moon-dev bash -c 'source ~/.cargo/env && cd /Users/tindang/workspaces/tind-repo/moon && \\"
    echo "  cargo test --features console && \\"
    echo "  cargo clippy --features console -- -D warnings'"
    echo '```'
    echo
    echo "## Caveats"
    echo
    echo "- This file is template-generated; narrative polish is out of scope for v0.1.5."
    echo "- Re-run \`bash scripts/gen-verification.sh\` after any PLAN or SUMMARY edit to refresh."
  } > "$out"

  echo "[gen-verification] wrote ${out}"
done
